---
apiVersion: v1
kind: Namespace
metadata:
  name: app-config-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-config-controller
  namespace: app-config-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-config-controller
rules:
- apiGroups: ["ac.io"]
  resources: ["appconfigs"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-config-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-config-controller
subjects:
- kind: ServiceAccount
  name: app-config-controller
  namespace: app-config-ns
