---
apiVersion: v1
kind: Namespace
metadata:
  name: app-config-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-config-controller
  namespace: app-config-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-config-controller
rules:
  - apiGroups: ["ac.io"]
    resources: ["appconfigs"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create","delete","get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-config-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-config-controller
subjects:
  - kind: ServiceAccount
    name: app-config-controller
    namespace: app-config-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-config-controller
  namespace: app-config-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-config-controller
  template:
    metadata:
      labels:
        app: app-config-controller
    spec:
      serviceAccountName: app-config-controller
      containers:
        - name: controller
          image: docker.io/enzhine/app-config-controller:v1
          imagePullPolicy: Always
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appconfigs.ac.io
spec:
  group: ac.io
  names:
    kind: AppConfig
    plural: appconfigs
    singular: appconfig
    shortNames:
      - ac
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - appName
                - namespace
                - data
              properties:
                appName:
                  type: string
                  pattern: ^[a-zA-Z0-9_-]*$
                namespace:
                  type: string
                  pattern: ^[a-zA-Z0-9_-]*$
                data:
                  type: object
                  additionalProperties: true
            status:
              type: object
              properties:
                lastUpdated:
                  type: string
                  format: date-time
